services:
  - type: web
    name: aidex-code-breakers
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://Anand:anand123@cluster0.bn7dvbg.mongodb.net/code-breakers?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: codebreakers_secret_key_2026
