services:
  - type: web
    name: aidex-backend
    runtime: node
    buildCommand: npm install --prefix server
    startCommand: npm --prefix server start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
      - key: MONGODB_URI
        value: mongodb+srv://Anand:anand123@cluster0.bn7dvbg.mongodb.net/code-breakers?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: codebreakers_secret_key_2026
